POST http://localhost:4004/odata/v4/order/approveOrder
Content-Type: application/json

{
    "orderID": "O003"
}

###
POST http://localhost:4004/odata/v4/order/askAI
Content-Type: application/json

{
    "question": "O que é SAP CAP?"
}

####
POST http://localhost:4004/odata/v4/order/askSQL
Content-Type: application/json

{
    "question": "Quantas ordens existem na base de dados"
}


####
POST http://localhost:4004/odata/v4/order/orders
Content-Type: application/json

{
  "numero": "OC006",
  "data": "2025-03-04T09:00:00Z",
  "valor_total": 95.00,
  "status": "PENDENTE",
  "fornecedor_ID": "f1",
  "previsao_entrega": "2025-03-07T09:00:00Z",
  "data_entrega": "2025-03-07T08:30:00Z",
  "materiais": [
    {
      "material_ID": "m1",
      "quantidade": 10,
      "preco_unitario": 0.50
    },
    {
      "material_ID": "m3",
      "quantidade": 2,
      "preco_unitario": 15.00
    }
  ]
}


####
POST http://localhost:4004/odata/v4/order/orders
Content-Type: application/json

{
  "numero": "OC007",
  "data": "2025-03-04T11:00:00Z",
  "valor_total": 400.00,
  "status": "PENDENTE",
  "fornecedor_ID": "f3",
  "previsao_entrega": "2025-03-06T11:00:00Z",
  "data_entrega": "2025-03-10T15:00:00Z",
  "materiais": [
    {
      "material_ID": "m4",
      "quantidade": 5,
      "preco_unitario": 28.00
    },
    {
      "material_ID": "m5",
      "quantidade": 10,
      "preco_unitario": 7.50
    }
  ]
}

